# This file contains values from Cookiecutter

default_context:
  project_name: "pdf_ask"
  project_description: "Awesome `pdf_ask` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "Alan Tetich"
  license: "MIT"
  minimal_python_version: 3.12
  github_name: "alan_tetich"
  email: "alan.tetich+work@gmail.com"
  version: "0.1.0"
  line_length: "120"
  create_example_template: "none"
